[package]
name = "vail"
version = "0.1.0"
authors = ["Hasan Ibraheem <hasantiny@gmail.com>"]
build = "build.rs"
license = "MPL-2.0"

[dependencies]

[build-dependencies]
regex = "0.2"
lazy_static = "1.0"
