[package]
name = "vail"
version = "0.1.0"
build = "build.rs"
authors = ["Juan Potato <hasantiny@gmail.com>", "Brayden Banks <bb010g@gmail.com>"]

[dependencies]
tl_derive = { path = "../tl_derive" }

[build-dependencies]
regex = "0.2"
lazy_static = "0.2"
